version: '3.8'

services:
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    working_dir: /app
    network_mode: "bridge"
    entrypoint: python main.py
